from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
from ase.io import read
from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap, CommentedSeq
import seekpath

from dftkit.schemas.vasp.input_files import BandPathInput

yaml = YAML()
yaml.default_flow_style = False


def _flow_seq(values: list[Any]) -> CommentedSeq:
    seq = CommentedSeq(values)
    seq.fa.set_flow_style()
    return seq


def _seekpath_data_from_poscar(input_path: Path) -> dict[str, Any]:
    atoms = read(input_path, format="vasp")
    cell = (
        np.array(atoms.cell.array, dtype=float),
        np.array(atoms.get_scaled_positions(), dtype=float),
        np.array(atoms.get_atomic_numbers(), dtype=int),
    )
    return seekpath.get_path(cell)


def _special_point_distances(path_data: dict[str, Any]) -> list[dict[str, Any]]:
    reciprocal_primitive = np.array(path_data["reciprocal_primitive_lattice"], dtype=float)
    point_coords = path_data["point_coords"]
    distances: list[dict[str, Any]] = []
    cumulative = 0.0
    last_label: str | None = None

    for start, end in path_data["path"]:
        start_frac = np.array(point_coords[start], dtype=float)
        end_frac = np.array(point_coords[end], dtype=float)
        start_cart = start_frac @ reciprocal_primitive
        end_cart = end_frac @ reciprocal_primitive

        if not distances:
            distances.append(
                {
                    "label": start,
                    "coords": [round(float(value), 8) for value in start_frac.tolist()],
                    "distance": round(cumulative, 8),
                }
            )
        elif last_label != start:
            previous = distances[-1]
            if round(previous["distance"], 8) == round(cumulative, 8):
                previous["label"] = f"{previous['label']}|{start}"
            else:
                distances.append(
                    {
                        "label": start,
                        "coords": [round(float(value), 8) for value in start_frac.tolist()],
                        "distance": round(cumulative, 8),
                    }
                )

        cumulative += float(np.linalg.norm(end_cart - start_cart))
        end_distance = round(cumulative, 8)
        if not (
            distances
            and distances[-1]["label"].split("|")[-1] == end
            and distances[-1]["distance"] == end_distance
        ):
            distances.append(
                {
                    "label": end,
                    "coords": [round(float(value), 8) for value in end_frac.tolist()],
                    "distance": end_distance,
                }
            )
        last_label = end

    return distances


def _format_fraction(value: float) -> str:
    rounded = round(float(value), 8)
    if abs(rounded) < 1e-8:
        return "0"
    if abs(rounded - 0.5) < 1e-8:
        return "1/2"
    if abs(rounded + 0.5) < 1e-8:
        return "-1/2"
    if abs(rounded - 1.0) < 1e-8:
        return "1"
    if abs(rounded + 1.0) < 1e-8:
        return "-1"
    return f"{rounded:.8f}".rstrip("0").rstrip(".")


def _render_band_label(label: str) -> str:
    return "$\\Gamma$" if label == "GAMMA" else label


def _band_strings(path_data: dict[str, Any]) -> tuple[str, str]:
    points = path_data["point_coords"]
    grouped_labels: list[list[str]] = []
    for start, end in path_data["path"]:
        if not grouped_labels or grouped_labels[-1][-1] != start:
            grouped_labels.append([start, end])
        else:
            grouped_labels[-1].append(end)

    band_segments: list[str] = []
    label_segments: list[str] = []
    for group in grouped_labels:
        coords_tokens: list[str] = []
        for label in group:
            coords_tokens.append(" ".join(_format_fraction(value) for value in points[label]))
        band_segments.append(" ".join(coords_tokens))
        label_segments.append(" ".join(_render_band_label(label) for label in group))
    return ", ".join(band_segments), ", ".join(label_segments)


def _write_band_kpoints(path: Path, path_data: dict[str, Any], line_density: int) -> None:
    lines = [
        f"Band path generated by dftkit (line_density={line_density})",
        str(line_density),
        "Line-Mode",
        "Reciprocal",
    ]
    point_coords = path_data["point_coords"]
    for start, end in path_data["path"]:
        start_coords = point_coords[start]
        end_coords = point_coords[end]
        lines.append(
            f"{start_coords[0]: .8f} {start_coords[1]: .8f} {start_coords[2]: .8f} ! {start}"
        )
        lines.append(
            f"{end_coords[0]: .8f} {end_coords[1]: .8f} {end_coords[2]: .8f} ! {end}"
        )
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8", newline="\n")


def _write_kpath_yaml(path: Path, path_data: dict[str, Any], line_density: int) -> None:
    special_distances = _special_point_distances(path_data)
    band, band_labels = _band_strings(path_data)
    points = CommentedMap()
    for label, coords in sorted(path_data["point_coords"].items()):
        points[label] = _flow_seq([round(float(value), 8) for value in coords])

    path_groups = _flow_seq(
        [
            _flow_seq(group.split())
            for group in band_labels.replace("$\\Gamma$", "GAMMA").replace(",", " , ").split(" , ")
        ]
    )

    distances = [item["distance"] for item in special_distances]
    payload = CommentedMap()
    payload["line_density"] = line_density
    payload["band"] = band
    payload["band_labels"] = band_labels
    payload["points"] = points
    payload["path"] = path_groups
    payload["special_distances"] = CommentedMap(
        {
            "labels": _flow_seq([item["label"] for item in special_distances]),
            "values": _flow_seq(distances),
            "values_2pi": _flow_seq([round(value / (2.0 * np.pi), 8) for value in distances]),
        }
    )
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        yaml.dump(payload, handle)


def run_band_kpoints_prepare(task_input: BandPathInput) -> dict[str, Any]:
    path_data = _seekpath_data_from_poscar(task_input.input)
    _write_band_kpoints(task_input.output, path_data, task_input.line_density)
    special_distances = _special_point_distances(path_data)
    _write_kpath_yaml(task_input.kpath_output, path_data, task_input.line_density)
    return {
        "task": "band-kpoints-prepare",
        "input": str(task_input.input),
        "output": str(task_input.output),
        "kpath_output": str(task_input.kpath_output),
        "line_density": task_input.line_density,
        "point_count": len(path_data["point_coords"]),
        "path_segment_count": len(path_data["path"]),
        "special_kpoint_count": len(special_distances),
    }
