from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np
from ase.io import read

from dftkit.schemas.vasp.input_files import KpointsMeshInput


def _kpoint_grid_from_kpr(lattice: np.ndarray, kpr: float) -> tuple[int, int, int]:
    reciprocal = np.linalg.inv(lattice).T
    lengths = np.linalg.norm(reciprocal, axis=1)
    grid = np.maximum(1, np.ceil(lengths / kpr).astype(int))
    return int(grid[0]), int(grid[1]), int(grid[2])


def _write_kpoints(path: Path, mode: str, grid: tuple[int, int, int], kpr: float) -> None:
    mode_label = "Gamma" if mode == "gamma" else "Monkhorst-Pack"
    text = (
        f"Automatic mesh generated by dftkit (kpr={kpr:.5f})\n"
        "0\n"
        f"{mode_label}\n"
        f"{grid[0]} {grid[1]} {grid[2]}\n"
        "0 0 0\n"
    )
    path.write_text(text, encoding="utf-8", newline="\n")


def run_kpoints_mesh(task_input: KpointsMeshInput) -> dict[str, Any]:
    atoms = read(task_input.input, format="vasp")
    lattice = np.array(atoms.cell.array, dtype=float)
    grid = _kpoint_grid_from_kpr(lattice, task_input.kpr)
    _write_kpoints(task_input.output, task_input.mode, grid, task_input.kpr)
    return {
        "task": "kpoints-mesh-generate",
        "input": str(task_input.input),
        "output": str(task_input.output),
        "mode": "Gamma" if task_input.mode == "gamma" else "Monkhorst-Pack",
        "kpr": task_input.kpr,
        "grid": list(grid),
    }
